name: Get whatsapp data

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Data scraping job
  Scraping:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data_scraping
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Get attachment
        run: npm run get:attachment
        env:
          FACEBOOK_EMAIL: ${{ secrets.GMAIL_USER }}
          FACEBOOK_PASS: ${{ secrets.GMAIL_PASS }}
